version: "3.9"
services:
  gateway:
    build: ./gateway
    ports: ["8000:8000"]
    depends_on: [human-detection, vehicle-detection, face-detection, anpr, suspicious-activity]

  human-detection:
    build: ./services/human-detection
    ports: ["8001:8001"]

  vehicle-detection:
    build: ./services/vehicle-detection
    ports: ["8002:8002"]

  face-detection:
    build: ./services/face-detection
    ports: ["8003:8003"]

  anpr:
    build: ./services/anpr
    ports: ["8004:8004"]

  suspicious-activity:
    build: ./services/suspicious-activity
    ports: ["8005:8005"]